In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
import nibabel as nib
import nilearn
from nilearn import plotting

In [4]:
#path = '/Users/katja/naturalCoordinates/2016-12_3DEmbryoAtlas/CS21/3DAtlas_CS21-7254-grey-v2016-01_d.nii.gz'
pathSeg =  
anat = nib.load( path )

In [5]:
#don't you dare plotting that big guy :P ohhhhh my! 798MB uchar!
#plotting.plot_anat( anat )

In [6]:
affine = anat.affine
print( affine )

[[ -1.00000000e+00   0.00000000e+00   0.00000000e+00   8.64500000e+02]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00  -1.88700000e+03]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00  -1.44000000e+02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [7]:
hdr = anat.header
print( hdr )
#hdr.set_sform( affine )


<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : 
db_name         : 
extents         : 0
session_error   : 0
regular         : 
dim_info        : 0
dim             : [   3 1729 3774  288    1    1    1    1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : uint8
bitpix          : 8
slice_start     : 0
pixdim          : [-1.  1.  1.  1.  0.  1.  1.  1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : FreeSurfer Jan 19 2017
aux_file        : 
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 1.0
quatern_d       : 0.0
qoffset_x       : 864.5
qoffset_y       : -1887.0
qoffset_z       : -144.0
srow_x          : [  -1. 

In [14]:
#pixdim is 1,1,1 --> but in fact we need 13.35 in z stack to unsquish it
#anat.header.get_zooms() --> 1,1,1 
anat.header.set_zooms( [1,1,13.35] )
print( anat.affine )

In [22]:
anat.affine[2][2] = 13.35

In [23]:
anat.affine

array([[ -1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          8.64500000e+02],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
         -1.88700000e+03],
       [  0.00000000e+00,   0.00000000e+00,   1.33500000e+01,
         -1.44000000e+02],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00]])

In [24]:
nib.save(anat,'myanat.nii.gz')

In [25]:
%%bash
open .

In [ ]:
#even better workflow:
#open file in FiJi
#image --> scale --Y and downsample here! e.g. 0.25!!! 
#--> save as analyze!


#the file opens in mricron, but looks all squished, still! :/
#it doesn't open in mango (it is too big (783MB)

#WORKFLOW:
#FiJi --> open application; open file --> .tiff --> save as analyze

#mri_convert complains about 'cannot determine filetype for .....file.hdr // unsopported data type 0
#so, open with mricron --> open heade information --> chose header img and hdr separately --> save as analyze again

#mri_convert -odt uchar /anat.img anat.nii.gz

#check
#ls -hal anat.nii.gz


#open in stereotaxic ramon (I can't seem to move between slices, but it displays one image)
#info()
#((
#-->get rid iof the 13.35 again :
#changePixdim(1,1,1)
#))

#resample(4,4,1,trilinear) --> 
#Volume size:	4,433,944,288,1
#Voxel units:	2,8
#Data type:		uchar
#Voxel size:	-1,2,2,6.675
#changePixdim(1,1,3.342)
#info to crosscheck

#save as nifti 
#gzip it

#check orientation/ flip
#open the 3D pdf and crosscheck



















#WORKFLOW:
#FiJi --> open application; open file --> .tiff --> save as analyze
#compalins about 'cannot determine filetype for .....file.hdr ÖÖ
#so, open with mricron
#change data type
#mri_convert -odt uchar anat.hdr anat.nii.gz
#mri_convert -odt uchar /anat.img anat.nii.gz

#check
#ls -hal /Users/katja/naturalCoordinates/2016-12_3DEmbryoAtlas/CS21/3DAtlas_CS21-7254-grey-v2016-01_d.nii.gz

#open in stereotaxic ramon (I can't seem to move between slices, but it displays one image)
#info()
#-->get rid iof the 13.35 again :
#changePixdim(1,1,1)
#
#resample(2,2,6.675,trilinear) --> 
#Volume size:	4,433,944,288,1
#Voxel units:	2,8
#Data type:		uchar
#Voxel size:	-1,2,2,6.675
#changePixdim(1,1,3.342)